import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import PageCss from "../components/PageCss";
import { useAuth } from "../auth/AuthContext";
import { useCourses } from "../context/CourseContext";
import api from "../services/api";

export default function MyCourses(){
  const {session}=useAuth(); const {courses}=useCourses(); const [enrolled,setEnrolled]=useState([]); const [progress,setProgress]=useState([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{async function load(){if(!session||session.role!=="student"){setLoading(false);return;}try{const [e,p]=await Promise.all([api.get(`/enrollments?username=${encodeURIComponent(session.username)}`),api.get(`/progress?username=${encodeURIComponent(session.username)}`)]);setEnrolled(e.data||[]);setProgress(p.data||[]);}catch(err){console.error(err);}finally{setLoading(false);}}load();},[session]);
  const getProgress=code=>progress.find(p=>String(p.courseCode).toLowerCase()===String(code).toLowerCase())||{progress:0,completed:false};
  return <><PageCss hrefs={["/css/style.css","/css/dashboard.css","/css/responsive.css"]}/><div className="dash-shell"><aside className="sidebar"><Link to="/" className="brand"><span className="brand-mark">E</span>Edu<span style={{color:"var(--gold-light)"}}>Ledger</span></Link><nav><Link to="/student-dashboard"><i className="fa-solid fa-gauge"/> Dashboard</Link><Link to="/my-courses" className="active"><i className="fa-solid fa-book-open"/> My Courses</Link><Link to="/courses"><i className="fa-solid fa-layer-group"/> Browse Catalog</Link><Link to="/saved-courses"><i className="fa-solid fa-bookmark"/> Saved Courses</Link><Link to="/certificates"><i className="fa-solid fa-certificate"/> Certificates</Link><Link to="/profile"><i className="fa-regular fa-user"/> Profile</Link></nav><div className="sidebar-foot"><Link to="/" className="logout"><i className="fa-solid fa-right-from-bracket"/> Logout</Link></div></aside><main className="dash-main"><div className="dash-topbar"><div><div className="breadcrumb">Student Portal</div><h1>My Courses</h1></div></div><div className="dash-body"><div className="welcome-banner"><div><h2>Your learning plan</h2><p>Continue active courses, review completed courses, and open certificates.</p></div><Link to="/courses" className="btn btn-primary">Browse Catalog</Link></div>{loading?<div className="placeholder-box">Loading your courses...</div>:enrolled.length===0?<div className="placeholder-box">No enrolled courses yet. <Link to="/courses">Browse the catalog</Link> to enroll.</div>:enrolled.map(e=>{const c=courses.find(x=>String(x.courseCode||x.code).toLowerCase()===String(e.courseCode).toLowerCase());if(!c)return null;const p=getProgress(e.courseCode);return <div className="panel" style={{marginBottom:16}} key={e.id}><div className="panel-head"><div><h3>{c.courseName||c.name}</h3><p style={{margin:0,color:"var(--muted-dim)"}}>{c.courseCode||c.code} · {c.instructor}</p></div><span className={`pill ${p.completed?"active":""}`}>{p.completed?"Completed":`${p.progress||0}%`}</span></div><p>{c.overview||c.desc}</p><div className="progress-row"><div className="progress-label"><span>Progress</span><span>{p.progress||0}%</span></div><div className="progress-bar"><span style={{width:`${p.progress||0}%`}}/></div></div><Link className="btn btn-primary btn-sm" to={`/course-learning?course=${encodeURIComponent(c.courseCode||c.code)}`}>{p.completed?"Review Course":"Continue Learning"}</Link>{p.completed&&<Link className="btn btn-ghost btn-sm" style={{marginLeft:8}} to={`/certificate?course=${encodeURIComponent(c.courseCode||c.code)}`}>Certificate</Link>}</div>})}</div></main></div></>;
}
