import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import PageCss from "../components/PageCss";
import { useAuth } from "../auth/AuthContext";
import { useCourses } from "../context/CourseContext";
import api from "../services/api";

export default function SavedCourses(){
  const {session}=useAuth(); const {courses}=useCourses(); const [saved,setSaved]=useState([]); const [loading,setLoading]=useState(true);
  async function load(){if(!session||session.role!=="student"){setLoading(false);return;}try{const r=await api.get(`/savedCourses?username=${encodeURIComponent(session.username)}`);setSaved(r.data||[]);}catch(e){console.error(e);}finally{setLoading(false);}}
  useEffect(()=>{load();},[session]);
  async function remove(id){try{await api.delete(`/savedCourses/${id}`);setSaved(x=>x.filter(s=>s.id!==id));}catch(e){console.error(e);}}
  return <><PageCss hrefs={["/css/style.css","/css/dashboard.css","/css/responsive.css"]}/><div className="dash-shell"><aside className="sidebar"><Link to="/" className="brand"><span className="brand-mark">E</span>Edu<span style={{color:"var(--gold-light)"}}>Ledger</span></Link><nav><Link to="/student-dashboard"><i className="fa-solid fa-gauge"/> Dashboard</Link><Link to="/my-courses"><i className="fa-solid fa-book-open"/> My Courses</Link><Link to="/courses"><i className="fa-solid fa-layer-group"/> Browse Catalog</Link><Link to="/saved-courses" className="active"><i className="fa-solid fa-bookmark"/> Saved Courses</Link><Link to="/certificates"><i className="fa-solid fa-certificate"/> Certificates</Link><Link to="/profile"><i className="fa-regular fa-user"/> Profile</Link></nav><div className="sidebar-foot"><Link to="/" className="logout"><i className="fa-solid fa-right-from-bracket"/> Logout</Link></div></aside><main className="dash-main"><div className="dash-topbar"><div><div className="breadcrumb">Student Portal</div><h1>Saved Courses</h1></div></div><div className="dash-body"><div className="welcome-banner"><div><h2>Your saved learning list</h2><p>Bookmark courses from the course details page and keep them ready for later.</p></div><Link to="/courses" className="btn btn-primary">Browse Catalog</Link></div>{loading?<div className="placeholder-box">Loading saved courses...</div>:saved.length===0?<div className="placeholder-box">No saved courses yet. <Link to="/courses">Browse the catalog</Link> and choose View Course.</div>:<div className="grid-3">{saved.map(s=>{const c=courses.find(x=>String(x.courseCode||x.code).toLowerCase()===String(s.courseCode).toLowerCase());if(!c)return null;return <div className="panel" key={s.id}><h3>{c.courseName||c.name}</h3><p>{c.overview||c.desc}</p><p style={{color:"var(--muted-dim)"}}>{c.courseCode||c.code} · {c.instructor}</p><Link className="btn btn-primary btn-sm" to={`/course-learning?course=${encodeURIComponent(c.courseCode||c.code)}`}>View Course</Link><button type="button" className="btn btn-ghost btn-sm" style={{marginLeft:8}} onClick={()=>remove(s.id)}>Remove</button></div>})}</div>}</div></main></div></>;
}
